name: Ciao
options:
  bundleIdPrefix: xyz.tavares
targets:
  Ciao:
    type: framework
    platform: [iOS, tvOS, macOS]
    deploymentTarget: "9.0"
    settings:
      MACOSX_DEPLOYMENT_TARGET: 10.9
    sources: Sources/Ciao
    scheme:
      testTargets:
        - CiaoTests_$platform
  CiaoTests:
    type: bundle.unit-test
    platform: [iOS, tvOS, macOS]
    sources: Tests/CiaoTests
    dependencies:
      - target: Ciao_$platform
